const jobListings = [
  {
    id: 1,
    title: "Frontend Developer",
    location: "Remote",
    description: "Develop UI using React.js and Tailwind CSS.",
    requirements: "Experience with React, Tailwind, and Git.",
  },
  {
    id: 2,
    title: "Backend Developer",
    location: "New York",
    description: "Develop API services using Node.js and MongoDB.",
    requirements: "Experience with Node.js, MongoDB, and REST APIs.",
  },
  {
    id: 3,
    title: "Full Stack Developer",
    location: "San Francisco",
    description: "Full stack development using MERN stack.",
    requirements: "Experience with MongoDB, Express, React, and Node.js.",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    location: "Remote",
    description: "Design user interfaces and experiences.",
    requirements: "Experience with Figma, Adobe XD, and user research.",
  },
  {
    id: 5,
    title: "DevOps Engineer",
    location: "London",
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    requirements: "Experience with AWS, Docker, Kubernetes, and Jenkins.",
  },
  {
    id: 6,
    title: "Frontend Developer",
    location: "Remote",
    description: "Develop UI using React.js and Tailwind CSS.",
    requirements: "Experience with React, Tailwind, and Git.",
  },
  {
    id: 7,
    title: "Backend Developer",
    location: "New York",
    description: "Develop API services using Node.js and MongoDB.",
    requirements: "Experience with Node.js, MongoDB, and REST APIs.",
  },
  {
    id: 8,
    title: "Full Stack Developer",
    location: "San Francisco",
    description: "Full stack development using MERN stack.",
    requirements: "Experience with MongoDB, Express, React, and Node.js.",
  },
  {
    id: 9,
    title: "UI/UX Designer",
    location: "Remote",
    description: "Design user interfaces and experiences.",
    requirements: "Experience with Figma, Adobe XD, and user research.",
  },
  {
    id: 10,
    title: "DevOps Engineer",
    location: "London",
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    requirements: "Experience with AWS, Docker, Kubernetes, and Jenkins.",
  },
  {
    id: 11,
    title: "Frontend Developer",
    location: "Remote",
    description: "Develop UI using React.js and Tailwind CSS.",
    requirements: "Experience with React, Tailwind, and Git.",
  },
  {
    id: 12,
    title: "Backend Developer",
    location: "New York",
    description: "Develop API services using Node.js and MongoDB.",
    requirements: "Experience with Node.js, MongoDB, and REST APIs.",
  },
  {
    id: 13,
    title: "Full Stack Developer",
    location: "San Francisco",
    description: "Full stack development using MERN stack.",
    requirements: "Experience with MongoDB, Express, React, and Node.js.",
  },
  {
    id: 14,
    title: "UI/UX Designer",
    location: "Remote",
    description: "Design user interfaces and experiences.",
    requirements: "Experience with Figma, Adobe XD, and user research.",
  },
  {
    id: 15,
    title: "DevOps Engineer",
    location: "London",
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    requirements: "Experience with AWS, Docker, Kubernetes, and Jenkins.",
  },
  {
    id: 16,
    title: "Frontend Developer",
    location: "Remote",
    description: "Develop UI using React.js and Tailwind CSS.",
    requirements: "Experience with React, Tailwind, and Git.",
  },
  {
    id: 17,
    title: "Backend Developer",
    location: "New York",
    description: "Develop API services using Node.js and MongoDB.",
    requirements: "Experience with Node.js, MongoDB, and REST APIs.",
  },
  {
    id: 18,
    title: "Full Stack Developer",
    location: "San Francisco",
    description: "Full stack development using MERN stack.",
    requirements: "Experience with MongoDB, Express, React, and Node.js.",
  },
  {
    id: 19,
    title: "UI/UX Designer",
    location: "Remote",
    description: "Design user interfaces and experiences.",
    requirements: "Experience with Figma, Adobe XD, and user research.",
  },
  {
    id: 20,
    title: "DevOps Engineer",
    location: "London",
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    requirements: "Experience with AWS, Docker, Kubernetes, and Jenkins.",
  },
];

export default jobListings;
